### ISSUE TITLE
Download link for pre-trained model is no longer working

### ISSUE THREAD

**Issue by stefanklut** [myungsub/CAIN#15]
Would it be possible to re-upload a pre-trained model (not necessarily to Dropbox), as I would like to use it in my research.

**Comment by stefanklut** [comment]
The SNU dataset download link is also not working

**Comment by HubertSotnowski** [comment]
I have downloaded pretrained. http://91.232.191.56/models/pretrained_cain.pth

**Comment by hiredd** [comment]
> I have downloaded pretrained. http://91.232.191.56/models/pretrained_cain.pth

SNU-FILM dataset is no longer working too  。。。

**Comment by HubertSotnowski** [comment]
i think i had snu  film dataset but idk where.

**Comment by BoyuanJiang** [comment]
> i think i had snu film dataset but idk where.

can you find the snu film dataset? I want to evaluate my algorithm on that.

**Comment by HubertSotnowski** [comment]
can't find.

**Comment by myungsub** [comment]
Thanks, everyone, for your interest, and so sorry for the late reply.
I remember changing the link availability a few months ago. Both (pretrained model + SNU-FILM dataset) links seem to be working currently, but please reopen this issue if it breaks again.
