### ISSUE TITLE
Feature map attention score

### ISSUE THREAD

**Issue by issakh** [myungsub/CAIN#18]
Hi, thanks for your work, it is pretty interesting. I have a question about the feature maps in figure 5. I know to obtain the feature maps you'd use hooks, but how do you manage to obtain the attention scores for the feature maps? 
Thanks again

**Comment by myungsub** [comment]
When I was drawing Figure 5, I temporarily changed the code of the channel attention layer (`CALayer`)to also output the attention scores. (You can see in some leftover unused code regarding the `self.return_ca` option)

**Comment by repers** [comment]
As the tensor returned is multi-channel, how do you find the high score. Do you sum up the pixel intensity values of each channel and then the one with the highest intensity is the one with most attention?
