### ISSUE TITLE
About exploding gradient

### ISSUE THREAD

**Issue by Heroandzhang** [myungsub/CAIN#19]
Hello, the code has exploding gradient problem in the vimeo90k dataset trained to 10epoch. If I start retraining from model_best.pth it will result in CUDA out of memory.
Q1. I have set both batch_size and test_batch_size to 8. Will this affect the final result?
Q2. Is there any other solution?
I would be grateful if you could reply!

**Comment by myungsub** [comment]
Hi @Heroandzhang , thanks for your interest in our work and sorry for the late reply.

Q1. Batch size (both training and test) shouldn't matter. Also, I think retraining from a checkpoint shouldn't use more memory than your initial training. Did you find a solution or any workaround to this issue? How large is your GPU memory?

Q2. It's been a while I looked into the training of CAIN.. Previously, just re-starting from a recent checkpoint worked for me, and I haven't searched for any other solutions. Sorry about that.

**Comment by Heroandzhang** [comment]
I'm sorry, but I can't find the solution

**Comment by myungsub** [comment]
Can you share the hardware setting for your experiments? What is your GPU memory size? Can you resume training with a batch size smaller than 8 (e.g. 4) ?

**Comment by Heroandzhang** [comment]
I am sorry that I am no longer doing this work so I cannot offer you any assistance.

**Comment by myungsub** [comment]
No problem. Then closing the issue for now.
