### ISSUE TITLE
how to convert the model to onnx？

### ISSUE THREAD

**Issue by hiredd** [myungsub/CAIN#3]
when i want to convert the model to the onnx  ,  but I can‘’t find   the input and output name of the model which  needed by torch.onnx.export(),  can you help me?  how to find the input and the output name?  thanks !

**Comment by myungsub** [comment]
Hi,
I have no experience with onnx,
but briefly looking at it docs, I think you can just specify input & output names as you want.
So, I guess you can just set it to something like

```python
input_names = ["input_1", "input_2"]
output_names = ["output_frame", "output_features"]
```

**Comment by hiredd** [comment]
good job!  thank you very much ~
