### ISSUE TITLE
Evaluation on UCF-101

### ISSUE THREAD

**Issue by tarun005** [myungsub/CAIN#5]
HI,

Can you explain how did you evaluate on the available test split of UCF-101? What frames are the inputs and outputs?

**Comment by myungsub** [comment]
Hi, thanks for your interest in our work.
We followed the settings from Voxelflow (you can download the preprocessed frames [[here](https://liuziwei7.github.io/projects/VoxelFlow)]), except that we did not use the motion masks for evaluation.
The inputs are `frame_00.png, frame_02.png`, and the target output is `frame_01_gt.png`.
We didn't do any fine-tuning for UCF-101, and just used these 379 triplets for evaluation.

**Comment by tarun005** [comment]
Thanks! Also, can you mention what is the time distance between these frames frame_00.png and frame_02.png? Similarly, what is the time gap (in seconds or milliseconds) between frames in Vimeo triplet and septuplet datasets?

**Comment by myungsub** [comment]
As I remember, UCF-101 was 30fps, which makes the time distance between `frame_00` and `frame_02` to be 1/15 sec. (~ 67ms).
I'm not sure about Vimeo90K datasets, but assuming that online existing videos are typically taken as 24fps or 30fps, I guess it should be about the same.
