### ISSUE TITLE
questions about PRETAINED MODEL

### ISSUE THREAD

**Issue by kankj** [myungsub/CAIN#8]
hello author, I found that your PRETRAINED MODEL link is not founded now, and I wonder if you could update it. Thanks

**Comment by myungsub** [comment]
Hi @kankj , the Dropbox download traffic has max-ed out, and it seems temporarily blocked.
Could you check if you can download the model using [[this link](https://drive.google.com/file/d/1BHy1gkejHxy-7vCwKczTb4Jviks8KOd3/view?usp=sharing)]?

**Comment by kankj** [comment]
It works fine, thank you very much
